import Head from 'next/head'
import { useEffect, useState } from 'react'
import JobDetail from '../../components/jobs/JobDetail'
import { useRouter } from 'next/router'
import LoadingSpinner from '../../components/ui/LoadingSpinner/LoadingSpinner'

type Props = {
    jobData: {
        id: string;
        title: string;
        location: {
            name: string;
        },
        content: any
    };
}

const JobDetailPage = () => {
    const jobId = useRouter().query.id;
    const [job, setJobs] = useState<any>([]);
    const [loading, setLoading] = useState<boolean>(true);
    const [error, setError] = useState<any>(null);

    useEffect(() => {
        if(!jobId) {
            return;
        }
        const fetchJobs = async () => {
            console.log('jobId', jobId);
            const res = await fetch(`http://localhost:3002/api/get-job/${jobId}`)

            if (!res.ok) {
                throw new Error('Something went wrong');
            }
            const data = await res.json()

            setJobs(data)
            setLoading(false)
        }

        try {
            fetchJobs()
        } catch (error) {

            setError(error)
        }
    }, [jobId])

    return <>
        <Head>
            <title>{job.title}</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        {/* <JobDetail location={jobData.location} content={jobData.content} title={jobData.title} /> */}
        {loading && <LoadingSpinner />}
        {!loading && !error && <JobDetail title={job.title} location={job.location} content={job.content} />}
        {error && <div>{error.message}</div>}
    </>
}

// export const getStaticProps = async (context: any) => {
//     const jobId = context.params.jobId;

//     const res = await fetch(`https://boards-api.greenhouse.io/v1/boards/unity3d/jobs/${jobId}`);
//     const data = await res.json();

//     return {
//         props: {
//             jobData: data
//         }
//     }
// }

// export const getStaticPaths = async () => {
//     const res = await fetch('https://boards-api.greenhouse.io/v1/boards/unity3d/jobs');
//     const data = await res.json();

//     const paths = data.jobs.map((job: any) => {
//         return {
//             params: {
//                 jobId: `${job.id}`
//             }
//         }
//     });

//     return {
//         paths,
//         fallback: false
//     }
// }

export default JobDetailPage;