version: '3'

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile-dev
    container_name: app
    restart: unless-stopped
    ports:
      - '3005:3000'
    env_file:
      - app.env
    volumes:
      - ../../:/home/node/app/
